<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="14" total="15" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-03-25T02:09:15Z" name="Default suite" finished-at="2024-03-25T02:09:22Z" duration-ms="6700">
    <groups>
    </groups>
    <test started-at="2024-03-25T02:09:15Z" name="Default test" finished-at="2024-03-25T02:09:22Z" duration-ms="6700">
      <class name="nuixc.testSuite.AdditionTests">
        <test-method is-config="true" signature="setup()[pri:0, instance:nuixc.testSuite.AdditionTests@3f67593e]" started-at="2024-03-25T02:09:15Z" name="setup" finished-at="2024-03-25T02:09:16Z" duration-ms="1317" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="test9digitNumbers()[pri:0, instance:nuixc.testSuite.AdditionTests@3f67593e]" started-at="2024-03-25T02:09:16Z" name="test9digitNumbers" finished-at="2024-03-25T02:09:22Z" duration-ms="5286" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[[Expected and Actual results doesn't matched.] 
expected: 1.23456789E9
 but was: 1.23466789E8]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: [Expected and Actual results doesn't matched.] 
expected: 1.23456789E9
 but was: 1.23466789E8
at nuixc.testSuite.AdditionTests.test9digitNumbers(AdditionTests.java:70)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test9digitNumbers -->
        <test-method is-config="true" signature="close()[pri:0, instance:nuixc.testSuite.AdditionTests@3f67593e]" started-at="2024-03-25T02:09:22Z" name="close" finished-at="2024-03-25T02:09:22Z" duration-ms="87" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- nuixc.testSuite.AdditionTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
